rzc_nam  ;equ *
     dta c'SZMAL', b(ASCZER)
     dta c'PIWO', b(ASCZER)
     dta c'KLUCZ', b(ASCZER)
     dta c'CYJANEK', b(ASCZER)
     dta c'OTWIERACZ', b(ASCZER)
     dta c'OTWARTE PIWO', b(ASCZER)
     dta c'ZATRUTE PIWO', b(ASCZER)
     dta c'BATERIA', b(ASCZER)
     dta b(PL_Z),c'AR',b(PL_O),'WECZKA', b(ASCZER)
     dta c'LATARKA', b(ASCZER)
     dta c'KOMPLETNA LATARKA', b(ASCZER)
     dta c'SMAR', b(ASCZER)
     dta c'SUCHAWKI LEKARSKIE', b(ASCZER)
     dta c'DETONATOR', b(ASCZER)
     dta c'SEKATOR', b(ASCZER)
     dta c'OPATA', b(ASCZER)
     dta c'DESKI', b(ASCZER)
     dta c'GAZ ZAWICY', b(ASCZER)
     dta c'DYNAMIT', b(ASCZER)
     dta c'WIADRO WODY', b(ASCZER)
     dta c'KIJ', b(ASCZER)
     dta c'TAMA KLEJCA', b(ASCZER)
     dta c'KINESKOP', b(ASCZER)
     dta c'BUTELKA', b(ASCZER)
     dta c'OPONA', b(ASCZER)
     dta c'DTKA', b(ASCZER)
     dta c'KSI',b(PL_Z),'KA', b(ASCZER)
     dta c'BUDZIK', b(ASCZER)
     dta c'KARABIN', b(ASCZER)
     dta c'LATARKA Z ',b(PL_Z),'AR',b(PL_O),'WK', b(ASCZER)
     dta c'LATARKA Z BATERI', b(ASCZER)
