rzc_nam  ;equ *
     dta c'CASH', b(ASCZER)
     dta c'BEER', b(ASCZER)
     dta c'KEY', b(ASCZER)
     dta c'CYANIDE', b(ASCZER)
     dta c'OPENER', b(ASCZER)
     dta c'OPENED BEER', b(ASCZER)
     dta c'POISONED BEER', b(ASCZER)
     dta c'BATTERY', b(ASCZER)
     dta c'BULB', b(ASCZER)
     dta c'TORCH', b(ASCZER)
     dta c'COMPLETE TORCH', b(ASCZER)
     dta c'GREASE', b(ASCZER)
     dta c'STETHOSCOPE', b(ASCZER)
     dta c'DETONATOR', b(ASCZER)
     dta c'SECATEUR', b(ASCZER)
     dta c'SPADE', b(ASCZER)
     dta c'BOARDS', b(ASCZER)
     dta c'TEAR GAS', b(ASCZER)
     dta c'DYNAMITE', b(ASCZER)
     dta c'BUCKET OF WATER', b(ASCZER)
     dta c'STICK', b(ASCZER)
     dta c'ADHESIVE TAPE', b(ASCZER)
     dta c'CINESCOPE', b(ASCZER)
     dta c'BOTTLE', b(ASCZER)
     dta c'TYRE', b(ASCZER)
     dta c'INNER TUBE', b(ASCZER)
     dta c'BOOK', b(ASCZER)
     dta c'ALARM CLOCK', b(ASCZER)
     dta c'RIFLE', b(ASCZER)
     dta c'TORCH WITH A BULB', b(ASCZER)
     dta c'TORCH WITH A BATTERY', b(ASCZER)
